#!/usr/bin/env python3
"""Generate a clickable macOS .app bundle that launches the workspace.

Usage:
    python scripts/build_launcher_app.py
    python scripts/build_launcher_app.py --output-dir ~/Desktop --port 8765
    python scripts/build_launcher_app.py --name "球分析工作台" --reinstall

What it builds:

    <output-dir>/<name>.app/
        Contents/
            Info.plist
            MacOS/
                launcher          (shell script, +x)
            Resources/
                project_path.txt  (absolute path to this repo)

Double-clicking the resulting .app:
    1. starts the workspace web server (.venv/bin/python scripts/12_serve_analysis_app.py)
    2. waits for the server to come up
    3. opens http://localhost:<port>/ in the default browser
    4. stays alive in Dock; quitting the app stops the server

The .app holds a hard path back to this repo. If you move the repo, run
this script again to regenerate.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path
from textwrap import dedent


PROJECT_ROOT = Path(__file__).resolve().parents[1]


INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>zh-CN</string>
    <key>CFBundleExecutable</key><string>launcher</string>
    <key>CFBundleIdentifier</key><string>local.football-analysis.workspace</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>{name}</string>
    <key>CFBundleDisplayName</key><string>{name}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>10.13</string>
    <key>LSUIElement</key><false/>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSHumanReadableCopyright</key><string>Local launcher for the Football Analysis workspace.</string>
</dict>
</plist>
"""


LAUNCHER_TEMPLATE = r"""#!/bin/bash
# Auto-generated by scripts/build_launcher_app.py
# Launches the football-analysis workspace, waits for it, then opens browser.

set -u
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_DIR="$(cat "$APP_DIR/Resources/project_path.txt")"
PORT="__PORT__"
URL="http://localhost:$PORT/"

dialog() {
    osascript -e "display dialog \"$1\" buttons {\"OK\"} default button 1 with icon caution with title \"足球分析工作台\""
}

notify() {
    osascript -e "display notification \"$1\" with title \"足球分析工作台\" subtitle \"$URL\""
}

if [ ! -d "$PROJECT_DIR" ]; then
    dialog "项目目录不存在: $PROJECT_DIR\\n请重新运行 scripts/build_launcher_app.py 重建启动器。"
    exit 1
fi

# TCC probe: try a no-op read on the project. macOS blocks .app access to
# ~/Documents by default, so the venv's symlinks can't be resolved at exec
# time and the launcher silently fails. Detect and explain.
if ! ls "$PROJECT_DIR/.venv/bin/" >/dev/null 2>&1; then
    osascript -e "display dialog \"macOS 阻止了启动器访问项目目录(~/Documents 默认受 TCC 保护)。\\n\\n请二选一:\\n\\n① 打开\\\"系统设置 → 隐私与安全 → 完全磁盘访问权限\\\",把 Football Analysis.app 加进去并启用,然后再次双击它。\\n\\n② 使用项目根的 \\\"打开工作台.command\\\" 文件,它在 Terminal 里跑,不需要 TCC 授权。\" buttons {\"打开系统设置\", \"知道了\"} default button 1 with icon caution with title \"足球分析工作台\""  -e "if button returned of result is \"打开系统设置\" then do shell script \"open 'x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles'\""
    exit 1
fi

cd "$PROJECT_DIR" || exit 1

if [ ! -x ".venv/bin/python" ]; then
    dialog "未找到 .venv/bin/python\\n请先在项目根创建虚拟环境并安装依赖。"
    exit 1
fi

# 已经在跑就直接打开浏览器
if curl -sf "$URL" >/dev/null 2>&1; then
    open "$URL"
    notify "已经在运行,已打开浏览器"
    # 仍然 wait,这样用户从 Dock 退出 app 时,我们不会留下孤儿 Python 进程
    # (没法 wait 一个不是自己启的进程,只好 sleep 长循环。)
    while curl -sf "$URL" >/dev/null 2>&1; do
        sleep 5
    done
    exit 0
fi

# 启动 server,把 stdout/stderr 落到日志
LOG_FILE="$PROJECT_DIR/data/launcher.log"
mkdir -p "$(dirname "$LOG_FILE")"
.venv/bin/python scripts/12_serve_analysis_app.py --port "$PORT" \
    > "$LOG_FILE" 2>&1 &
SERVER_PID=$!

# 用户从 Dock 退出 → 杀子进程
trap 'kill "$SERVER_PID" 2>/dev/null; exit 0' INT TERM EXIT

# 最多等 30 秒
for i in $(seq 1 60); do
    if curl -sf "$URL" >/dev/null 2>&1; then
        open "$URL"
        notify "工作台已就绪"
        wait "$SERVER_PID"
        exit 0
    fi
    sleep 0.5
done

dialog "服务启动超时,请查看 $LOG_FILE"
kill "$SERVER_PID" 2>/dev/null
exit 1
"""


WEBLOC_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>URL</key>
    <string>http://localhost:{port}/</string>
</dict>
</plist>
"""


# A .command file is a shell script with .command extension. macOS treats
# it as "double-click to run in Terminal". Terminal has TCC access to
# ~/Documents by default, so this bypasses the .app sandbox entirely.
COMMAND_TEMPLATE = r"""#!/bin/bash
# 双击在 Terminal 里启动工作台。Terminal 有 ~/Documents 访问权限,
# 不会被 TCC 拦截。Ctrl+C 停服务,关 Terminal 窗口也行。

PROJECT_DIR="__PROJECT_DIR__"
PORT="__PORT__"
URL="http://localhost:$PORT/"

cd "$PROJECT_DIR" || { echo "项目目录不存在: $PROJECT_DIR"; read -p "回车退出..."; exit 1; }

if [ ! -x ".venv/bin/python" ]; then
    echo "❌ 未找到 .venv/bin/python"
    echo "   请先在 $PROJECT_DIR 创建虚拟环境并安装依赖"
    read -p "回车退出..."
    exit 1
fi

# 已经在跑就直接打开浏览器
if curl -sf "$URL" >/dev/null 2>&1; then
    echo "✓ 服务已在 $URL 运行,直接打开浏览器。"
    open "$URL"
    read -p "(回车关闭此窗口,服务保持运行)"
    exit 0
fi

echo "▶ 启动 workspace web 服务: $URL"
echo "  (Ctrl+C 停止服务;关闭 Terminal 窗口也会停)"
echo ""

.venv/bin/python scripts/12_serve_analysis_app.py --port "$PORT" &
SERVER_PID=$!
trap 'kill "$SERVER_PID" 2>/dev/null; exit 0' INT TERM EXIT

# 等就绪后开浏览器
for i in $(seq 1 30); do
    if curl -sf "$URL" >/dev/null 2>&1; then
        open "$URL"
        echo "✓ 浏览器已打开: $URL"
        break
    fi
    sleep 0.5
done

wait "$SERVER_PID"
"""


def build_app(name: str, output_dir: Path, port: int, reinstall: bool) -> Path:
    app_path = output_dir / f"{name}.app"
    if app_path.exists():
        if not reinstall:
            raise SystemExit(
                f"⚠️  {app_path} 已存在。加 --reinstall 覆盖,或换 --name 改名。"
            )
        shutil.rmtree(app_path)

    contents = app_path / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    (contents / "Info.plist").write_text(
        INFO_PLIST.format(name=name), encoding="utf-8"
    )

    launcher = LAUNCHER_TEMPLATE.replace("__PORT__", str(port))
    launcher_path = macos / "launcher"
    launcher_path.write_text(launcher, encoding="utf-8")
    launcher_path.chmod(0o755)

    (resources / "project_path.txt").write_text(
        str(PROJECT_ROOT.resolve()), encoding="utf-8"
    )

    # Sister .webloc bookmark — drag to Dock for one-click "open in browser"
    # (independent of whether the .app is running; works after the service
    # is already started). Even when the .app is running, double-clicking the
    # .app does NOT re-trigger the launcher (macOS just focuses the existing
    # process), so a separate URL bookmark is the right reopen-the-page UX.
    webloc_path = output_dir / f"{name}（打开浏览器）.webloc"
    webloc_path.write_text(WEBLOC_TEMPLATE.format(port=port), encoding="utf-8")

    return app_path, webloc_path


def build_command_file(project_root: Path, port: int) -> Path:
    """Generate a .command file at the project root that bypasses .app TCC
    restrictions by launching in Terminal (which has ~/Documents access)."""
    cmd_path = project_root / "打开工作台.command"
    body = (
        COMMAND_TEMPLATE
        .replace("__PROJECT_DIR__", str(project_root.resolve()))
        .replace("__PORT__", str(port))
    )
    cmd_path.write_text(body, encoding="utf-8")
    cmd_path.chmod(0o755)
    return cmd_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--name", default="Football Analysis",
                        help="App display name (default: 'Football Analysis')")
    parser.add_argument("--output-dir", default="~/Applications",
                        help="Where to drop the .app (default: ~/Applications)")
    parser.add_argument("--port", type=int, default=8765,
                        help="Port the workspace will listen on (default: 8765, "
                             "matches 12_serve_analysis_app.py default)")
    parser.add_argument("--reinstall", action="store_true",
                        help="Overwrite if the .app already exists")
    args = parser.parse_args()

    output_dir = Path(args.output_dir).expanduser()
    if not output_dir.exists():
        try:
            output_dir.mkdir(parents=True)
        except OSError as exc:
            raise SystemExit(f"无法创建 {output_dir}: {exc}")

    if sys.platform != "darwin":
        print(f"⚠️  本脚本生成 macOS .app 包,当前系统是 {sys.platform};"
              " 仍然会生成,但可能无法直接双击运行。", file=sys.stderr)

    app_path, webloc_path = build_app(args.name, output_dir, args.port, args.reinstall)
    cmd_path = build_command_file(PROJECT_ROOT, args.port)
    url = f"http://localhost:{args.port}/"

    print(f"✅ macOS App 启动器:  {app_path}")
    print(f"✅ 浏览器 URL 书签:   {webloc_path}")
    print(f"✅ Terminal 启动文件: {cmd_path}")
    print(f"   关联项目:        {PROJECT_ROOT}")
    print(f"   工作台 URL:      {url}")
    print()
    print("使用建议:")
    print(f"   📱 {app_path.name} (~/Applications/)")
    print(f"      最 mac 原生。第一次双击 macOS 可能会问\"允许访问 Documents\",点允许。")
    print(f"      如果遇到 TCC 拦截:系统设置 → 隐私与安全 → 完全磁盘访问权限,加进去。")
    print()
    print(f"   ⚡ {cmd_path.name} (项目根目录)")
    print(f"      最稳。Finder 双击它会在 Terminal 里启动,不会被 macOS 隐私保护拦截。")
    print(f"      关闭 Terminal 窗口或 Ctrl+C 即停服务。")
    print(f"      第一次会问\"是否允许执行\",点允许。")
    print()
    print(f"   🌐 {webloc_path.name}")
    print(f"      服务起来后双击,就回到 {url}。可拖到 Dock 钉住。")
    print()
    print("项目搬家了?重新跑 scripts/build_launcher_app.py 即可。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
