#!/usr/bin/env python3
"""Generate a clickable macOS .app bundle that launches the workspace.

Usage:
    python scripts/build_launcher_app.py
    python scripts/build_launcher_app.py --output-dir ~/Desktop --port 8765
    python scripts/build_launcher_app.py --name "球分析工作台" --reinstall

What it builds:

    <output-dir>/<name>.app/
        Contents/
            Info.plist
            MacOS/
                launcher          (shell script, +x)
            Resources/
                project_path.txt  (absolute path to this repo)

Double-clicking the resulting .app:
    1. starts the workspace web server (.venv/bin/python scripts/12_serve_analysis_app.py)
    2. waits for the server to come up
    3. opens http://localhost:<port>/ in the default browser
    4. stays alive in Dock; quitting the app stops the server

The .app holds a hard path back to this repo. If you move the repo, run
this script again to regenerate.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path
from textwrap import dedent


PROJECT_ROOT = Path(__file__).resolve().parents[1]


INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>zh-CN</string>
    <key>CFBundleExecutable</key><string>launcher</string>
    <key>CFBundleIdentifier</key><string>local.football-analysis.workspace</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>{name}</string>
    <key>CFBundleDisplayName</key><string>{name}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>10.13</string>
    <key>LSUIElement</key><false/>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSHumanReadableCopyright</key><string>Local launcher for the Football Analysis workspace.</string>
</dict>
</plist>
"""


LAUNCHER_TEMPLATE = r"""#!/bin/bash
# Auto-generated by scripts/build_launcher_app.py
# Launches the football-analysis workspace, waits for it, then opens browser.

set -u
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_DIR="$(cat "$APP_DIR/Resources/project_path.txt")"
PORT="__PORT__"

dialog() {
    osascript -e "display dialog \"$1\" buttons {\"OK\"} default button 1 with icon caution with title \"足球分析工作台\""
}

if [ ! -d "$PROJECT_DIR" ]; then
    dialog "项目目录不存在: $PROJECT_DIR\\n请重新运行 scripts/build_launcher_app.py 重建启动器。"
    exit 1
fi

cd "$PROJECT_DIR" || exit 1

if [ ! -x ".venv/bin/python" ]; then
    dialog "未找到 .venv/bin/python\\n请先在项目根创建虚拟环境并安装依赖。"
    exit 1
fi

# 已经在跑就直接打开浏览器
if curl -sf "http://localhost:$PORT/" >/dev/null 2>&1; then
    open "http://localhost:$PORT/"
    # 仍然 wait,这样用户从 Dock 退出 app 时,我们不会留下孤儿 Python 进程
    # (没法 wait 一个不是自己启的进程,只好 sleep 长循环。)
    while curl -sf "http://localhost:$PORT/" >/dev/null 2>&1; do
        sleep 5
    done
    exit 0
fi

# 启动 server,把 stdout/stderr 落到日志
LOG_FILE="$PROJECT_DIR/data/launcher.log"
mkdir -p "$(dirname "$LOG_FILE")"
.venv/bin/python scripts/12_serve_analysis_app.py --port "$PORT" \
    > "$LOG_FILE" 2>&1 &
SERVER_PID=$!

# 用户从 Dock 退出 → 杀子进程
trap 'kill "$SERVER_PID" 2>/dev/null; exit 0' INT TERM EXIT

# 最多等 30 秒
for i in $(seq 1 60); do
    if curl -sf "http://localhost:$PORT/" >/dev/null 2>&1; then
        open "http://localhost:$PORT/"
        wait "$SERVER_PID"
        exit 0
    fi
    sleep 0.5
done

dialog "服务启动超时,请查看 $LOG_FILE"
kill "$SERVER_PID" 2>/dev/null
exit 1
"""


def build_app(name: str, output_dir: Path, port: int, reinstall: bool) -> Path:
    app_path = output_dir / f"{name}.app"
    if app_path.exists():
        if not reinstall:
            raise SystemExit(
                f"⚠️  {app_path} 已存在。加 --reinstall 覆盖,或换 --name 改名。"
            )
        shutil.rmtree(app_path)

    contents = app_path / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    (contents / "Info.plist").write_text(
        INFO_PLIST.format(name=name), encoding="utf-8"
    )

    launcher = LAUNCHER_TEMPLATE.replace("__PORT__", str(port))
    launcher_path = macos / "launcher"
    launcher_path.write_text(launcher, encoding="utf-8")
    launcher_path.chmod(0o755)

    (resources / "project_path.txt").write_text(
        str(PROJECT_ROOT.resolve()), encoding="utf-8"
    )
    return app_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--name", default="Football Analysis",
                        help="App display name (default: 'Football Analysis')")
    parser.add_argument("--output-dir", default="~/Applications",
                        help="Where to drop the .app (default: ~/Applications)")
    parser.add_argument("--port", type=int, default=8765,
                        help="Port the workspace will listen on (default: 8765, "
                             "matches 12_serve_analysis_app.py default)")
    parser.add_argument("--reinstall", action="store_true",
                        help="Overwrite if the .app already exists")
    args = parser.parse_args()

    output_dir = Path(args.output_dir).expanduser()
    if not output_dir.exists():
        try:
            output_dir.mkdir(parents=True)
        except OSError as exc:
            raise SystemExit(f"无法创建 {output_dir}: {exc}")

    if sys.platform != "darwin":
        print(f"⚠️  本脚本生成 macOS .app 包,当前系统是 {sys.platform};"
              " 仍然会生成,但可能无法直接双击运行。", file=sys.stderr)

    app_path = build_app(args.name, output_dir, args.port, args.reinstall)

    print(f"✅ 启动器已生成: {app_path}")
    print(f"   关联项目:   {PROJECT_ROOT}")
    print(f"   监听端口:   {args.port}")
    print()
    print("使用:")
    print(f"   open '{app_path}'        # 立即启动")
    print(f"   或在 Finder 双击它")
    print(f"   或拖到 Dock 钉住,以后一键启动")
    print()
    print("如果你将来移动了项目目录,重新跑 scripts/build_launcher_app.py 即可。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
